on: push

jobs:
  job_id:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v3'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          service_account: 'github-actions@velvety-study-367319.iam.gserviceaccount.com'
          credentials_json: ${{ secrets.GCP_SA }}

      - uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          image: 'gcr.io/cloudrun/hello'
          service: 'hello-cloud-run'
